apiVersion: v1
kind: Pod
metadata:
  name: dept-pod
  labels:
     zone: prod
     version: v1
spec:
  containers:
  - name: dept-cnt
    image: charantej224/dept1:1 
    ports:
    - containerPort: 8080
